name: Unit Testing

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          cd src
          python -m coverage run -m unittest
          python -m coverage xml
      # Runs a set of commands using the runners shell
      - name: Get coverage status
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t e28a01cc-e6ba-4264-bcbb-3c273182080e